////////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 1.11
//  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
//  /   /         Filename : s6_gtpwizard_v1_11_top.v
// /___/   /\      
// \   \  /  \ 
//  \___\/\___\
//
//
// Module s6_gtpwizard_v1_11_top
// Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard
// 
// 
// (c) Copyright 2009 - 2011 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1


//***********************************Entity Declaration************************

module s6_gtpwizard_v1_11_top #
(
    parameter EXAMPLE_CONFIG_INDEPENDENT_LANES          =   1,   //configuration for frame gen and check
    parameter EXAMPLE_LANE_WITH_START_CHAR              =   0,   // specifies lane with unique start frame char
    parameter EXAMPLE_WORDS_IN_BRAM                     =   512, // specifies amount of data in BRAM   
    parameter EXAMPLE_SIM_GTPRESET_SPEEDUP              =   0,   // simulation setting for GTP SecureIP model
    parameter EXAMPLE_USE_CHIPSCOPE                     =   1,    // Set to 1 to use Chipscope to drive resets
    parameter EXAMPLE_SIMULATION                        =   0    // Set to 1 in testbench for simulation
)
(
    input  wire          TILE0_GTP0_REFCLK_PAD_N_IN,
    input  wire          TILE0_GTP0_REFCLK_PAD_P_IN,
    input  wire          DRP_CLK_IN,
    input  wire          GTP0_RESET_IN,
    input  wire          GTP1_RESET_IN,
    output wire          TILE0_GTP0_PLLLKDET_OUT,
    output wire          TRACK_DATA_OUT,
    input  wire  [1:0]   RXN_IN,
    input  wire  [1:0]   RXP_IN,
    output wire  [1:0]   TXN_OUT,
    output wire  [1:0]   TXP_OUT
);

    
//************************** Register Declarations ****************************

    reg     [84:0]  ila_in0_r;
    reg     [84:0]  ila_in1_r;
    reg             tile0_resetdone0_r;
    reg             tile0_resetdone0_r2;
    reg             tile0_resetdone1_r;
    reg             tile0_resetdone1_r2;
    

//**************************** Wire Declarations ******************************

    //------------------------ MGT Wrapper Wires ------------------------------

    //________________________________________________________________________
    //________________________________________________________________________
    //TILE0   (X0_Y0)

    //---------------------- Loopback and Powerdown Ports ----------------------
    wire    [2:0]   tile0_loopback0_i;
    wire    [2:0]   tile0_loopback1_i;
    //------------------------------- PLL Ports --------------------------------
    wire            tile0_gtpreset0_i;
    wire            tile0_gtpreset1_i;
    wire            tile0_plllkdet0_i;
    wire            tile0_plllkdet1_i;
    wire            tile0_resetdone0_i;
    wire            tile0_resetdone1_i;
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    wire    [3:0]   tile0_rxchariscomma0_i;
    wire    [3:0]   tile0_rxchariscomma1_i;
    wire    [3:0]   tile0_rxcharisk0_i;
    wire    [3:0]   tile0_rxcharisk1_i;
    wire    [3:0]   tile0_rxdisperr0_i;
    wire    [3:0]   tile0_rxdisperr1_i;
    wire    [3:0]   tile0_rxnotintable0_i;
    wire    [3:0]   tile0_rxnotintable1_i;
    wire    [3:0]   tile0_rxrundisp0_i;
    wire    [3:0]   tile0_rxrundisp1_i;
    //------------- Receive Ports - Comma Detection and Alignment --------------
    wire            tile0_rxbyteisaligned0_i;
    wire            tile0_rxbyteisaligned1_i;
    wire            tile0_rxenmcommaalign0_i;
    wire            tile0_rxenmcommaalign1_i;
    wire            tile0_rxenpcommaalign0_i;
    wire            tile0_rxenpcommaalign1_i;
    //----------------- Receive Ports - RX Data Path interface -----------------
    wire    [31:0]  tile0_rxdata0_i;
    wire    [31:0]  tile0_rxdata1_i;
    wire            tile0_rxrecclk0_i;
    wire            tile0_rxrecclk1_i;
    wire            tile0_rxreset0_i;
    wire            tile0_rxreset1_i;
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    wire            tile0_rxelecidle0_i;
    wire            tile0_rxelecidle1_i;
    wire    [1:0]   tile0_rxeqmix0_i;
    wire    [1:0]   tile0_rxeqmix1_i;
    //--------- Receive Ports - RX Elastic Buffer and Phase Alignment ----------
    wire    [2:0]   tile0_rxstatus0_i;
    wire    [2:0]   tile0_rxstatus1_i;
    //-------------------------- TX/RX Datapath Ports --------------------------
    wire    [1:0]   tile0_gtpclkfbeast_i;
    wire    [1:0]   tile0_gtpclkfbwest_i;
    wire    [1:0]   tile0_gtpclkout0_i;
    wire    [1:0]   tile0_gtpclkout1_i;
    //----------------- Transmit Ports - 8b10b Encoder Control -----------------
    wire    [3:0]   tile0_txbypass8b10b0_i;
    wire    [3:0]   tile0_txbypass8b10b1_i;
    wire    [3:0]   tile0_txchardispmode0_i;
    wire    [3:0]   tile0_txchardispmode1_i;
    wire    [3:0]   tile0_txchardispval0_i;
    wire    [3:0]   tile0_txchardispval1_i;
    wire    [3:0]   tile0_txcharisk0_i;
    wire    [3:0]   tile0_txcharisk1_i;
    wire    [3:0]   tile0_txkerr0_i;
    wire    [3:0]   tile0_txkerr1_i;
    wire    [3:0]   tile0_txrundisp0_i;
    wire    [3:0]   tile0_txrundisp1_i;
    //------------- Transmit Ports - TX Buffer and Phase Alignment -------------
    wire            tile0_txenpmaphasealign0_i;
    wire            tile0_txenpmaphasealign1_i;
    wire            tile0_txpmasetphase0_i;
    wire            tile0_txpmasetphase1_i;
    //---------------- Transmit Ports - TX Data Path interface -----------------
    wire    [31:0]  tile0_txdata0_i;
    wire    [31:0]  tile0_txdata1_i;
    wire            tile0_txoutclk0_i;
    wire            tile0_txoutclk1_i;
    wire            tile0_txreset0_i;
    wire            tile0_txreset1_i;
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    wire    [3:0]   tile0_txdiffctrl0_i;
    wire    [3:0]   tile0_txdiffctrl1_i;
    wire    [2:0]   tile0_txpreemphasis0_i;
    wire    [2:0]   tile0_txpreemphasis1_i;
    //--------------- Transmit Ports - TX Ports for PCI Express ----------------
    wire            tile0_txelecidle0_i;
    wire            tile0_txelecidle1_i;
    //------------------- Transmit Ports - TX Ports for SATA -------------------
    wire            tile0_txcomstart0_i;
    wire            tile0_txcomstart1_i;
    wire            tile0_txcomtype0_i;
    wire            tile0_txcomtype1_i;


    //----------------------------- Global Signals -----------------------------
    wire            tile0_tx_system_reset0_c;
    wire            tile0_tx_system_reset1_c;
    wire            tile0_rx_system_reset0_c;
    wire            tile0_rx_system_reset1_c;
    wire            tied_to_ground_i;
    wire    [191:0] tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [7:0]   tied_to_vcc_vec_i;
    wire            drp_clk_in_i;
    wire            tile0_refclkout_bufg_i;
    
    
    //--------------------------- User Clocks ---------------------------------
    wire            tile0_txusrclk0_i;
    wire            tile0_txusrclk20_i;
    wire            tile0_rxusrclk0_i;
    wire            tile0_rxusrclk20_i;
    wire            tile0_rxusrclk1_i;
    wire            tile0_rxusrclk21_i;
    wire            gtpclkout0_0_pll0_locked_i;
    wire            gtpclkout0_0_pll0_reset_i;
    wire            tile0_gtpclkout0_0_to_cmt_i;
    wire            pll0_fb_out_i;
    wire            pll0_fb_in_i;
    wire            gtpclkout0_1_dcm1_locked_i;
    wire            gtpclkout0_1_dcm1_reset_i;
    wire            tile0_gtpclkout0_1_to_dcm_i;
    wire            gtpclkout1_1_dcm2_locked_i;
    wire            gtpclkout1_1_dcm2_reset_i;
    wire            tile0_gtpclkout1_1_to_dcm_i;


    //--------------------- Frame check/gen Module Signals --------------------
    wire            tile0_gtp0_refclk_i;

    wire            tile0_matchn0_i;
    wire    [7:0]   tile0_txdata0_float_i;
    wire            tile0_track_data0_i;
    wire    [7:0]   tile0_error_count0_i;
    wire            tile0_frame_check0_reset_i;
    wire            tile0_inc_in0_i;
    wire            tile0_inc_out0_i;
    wire            tile0_matchn1_i;
    wire    [7:0]   tile0_txdata1_float_i;
    wire            tile0_track_data1_i;
    wire    [7:0]   tile0_error_count1_i;
    wire            tile0_frame_check1_reset_i;
    wire            tile0_inc_in1_i;
    wire            tile0_inc_out1_i;

    wire            reset_on_data_error_i;
    wire            track_data_out_i;
    
    //----------------------- Sync Module Signals -----------------------------
    wire            tile0_rx_sync_done0_i;
    wire            tile0_rx_sync_done1_i;
    wire            tile0_tx_sync_done0_i;
    wire            tile0_tx_sync_done1_i;
    //--------------------- Chipscope Signals ---------------------------------

    wire    [35:0]  shared_vio_control_i;
    wire    [35:0]  tile0_data_vio_control_i;
    wire    [35:0]  tile0_gtp0_ila_control_i;
    wire    [35:0]  tile0_gtp1_ila_control_i;
    wire    [35:0]  null_vio_4_i;
    wire    [35:0]  null_vio_5_i;
    wire    [35:0]  null_vio_6_i;
    wire    [35:0]  null_vio_7_i;
    wire    [35:0]  null_vio_8_i;
    wire    [35:0]  null_vio_9_i;
    wire    [35:0]  null_vio_10_i;
    wire    [35:0]  null_vio_11_i;
    wire    [35:0]  null_vio_12_i;
    wire    [31:0]  shared_vio_in_i;
    wire    [31:0]  shared_vio_out_i;

    wire    [139:0] tile0_data_vio_in_i;
    wire    [139:0] tile0_data_vio_out_i;
    wire    [84:0]  tile0_ila_in0_i;
    wire    [84:0]  tile0_ila_in1_i;


    wire            gtpreset0_i;
    wire            gtpreset1_i;
    wire            user_tx_reset_i;
    wire            user_rx_reset_i;


//**************************** Main Body of Code *******************************

    //  Static signal Assigments    
    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 192'h000000000000000000000000000000000000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 8'hff;


   
    //---------------------------- DRP Clock ----------------------------------
    // The DRP interface requires an independent clock which can run up to about 210 MHz.
    // This design uses a 50 MHz DCLK from external pins. In your own design, the
    // clock can come from internal sources, but do not use TXOUTCLK or RXRECCLK
    // or your design may deadlock. REFCLKPLL can be used as a source.
    
    BUFG drp_clk_in_bufg_i
    (
        .I      (DRP_CLK_IN),
        .O      (drp_clk_in_i)
    );
    


    //---------------------Dedicated GTP Reference Clock Inputs ---------------
    // The dedicated reference clock inputs you selected in the GUI are implemented using
    // IBUFDS instances.
    //
    // In the UCF file for this example design, you will see that each of
    // these IBUFDS instances has been LOCed to a particular set of pins. By LOCing to these
    // locations, we tell the tools to use the dedicated input buffers to the GTP reference
    // clock network, rather than general purpose IOs. To select other pins, consult the 
    // Implementation chapter of UG___, or rerun the wizard.
    //
    // This network is the highest performace (lowest jitter) option for providing clocks
    // to the GTP transceivers.
    
    IBUFDS tile0_gtp0_refclk_ibufds_i
    (
        .O                              (tile0_gtp0_refclk_i),
        .I                              (TILE0_GTP0_REFCLK_PAD_P_IN),
        .IB                             (TILE0_GTP0_REFCLK_PAD_N_IN)
    );

    //--------------------------------- User Clocks ---------------------------
    
    // The clock resources in this section were added based on userclk source selections on
    // the Latency, Buffering, and Clocking page of the GUI. A few notes about user clocks:
    // * The userclk and userclk2 for each GTP datapath (TX and RX) must be phase aligned to 
    //   avoid data errors in the fabric interface whenever the datapath is wider than 10 bits
    // * To minimize clock resources, you can share clocks between GTPs. GTPs using the same frequency
    //   or multiples of the same frequency can be accomadated using DCMs and PLLs. Use caution when
    //   using RXRECCLK as a clock source, however - these clocks can typically only be shared if all
    //   the channels using the clock are receiving data from TX channels that share a reference clock 
    //   source with each other.

    BUFIO2 #
    (
        .DIVIDE                         (1),
        .DIVIDE_BYPASS                  ("TRUE")
    )
    gtpclkout0_0_pll0_bufio2_i
    (
        .I                              (tile0_gtpclkout0_i[0]),
        .DIVCLK                         (tile0_gtpclkout0_0_to_cmt_i),
        .IOCLK                          (),
        .SERDESSTROBE                   ()
    );

    BUFIO2FB #
    (
        .DIVIDE_BYPASS                  ("TRUE")
    )
    gtpclkout0_0_pll0_bufio2fb_i
    (
        .I                              (tile0_gtpclkfbwest_i[0]),
        .O                              (pll0_fb_in_i)
    );

    assign  gtpclkout0_0_pll0_reset_i       =  !tile0_plllkdet0_i;
    MGT_USRCLK_SOURCE_PLL #
    (
        .MULT                           (4),
        .DIVIDE                         (4),
        .FEEDBACK                       ("CLKOUT0"),
        .CLK_PERIOD                     (6.667),
        .OUT0_DIVIDE                    (4),
        .OUT1_DIVIDE                    (16),
        .OUT2_DIVIDE                    (1),
        .OUT3_DIVIDE                    (1)
    )
    gtpclkout0_0_pll0_i
    (
        .CLK0_OUT                       (tile0_txusrclk0_i),
        .CLK1_OUT                       (tile0_txusrclk20_i),
        .CLK2_OUT                       (),
        .CLK3_OUT                       (),
        .CLK_IN                         (tile0_gtpclkout0_0_to_cmt_i),
        .CLKFB_IN                       (pll0_fb_in_i),
        .CLKFB_OUT                      (pll0_fb_out_i),
        .PLL_LOCKED_OUT                 (gtpclkout0_0_pll0_locked_i),
        .PLL_RESET_IN                   (gtpclkout0_0_pll0_reset_i)
    );


    BUFIO2 #
    (
        .DIVIDE                         (1),
        .DIVIDE_BYPASS                  ("TRUE")
    )
    gtpclkout0_1_dcm1_bufio2_i
    (
        .I                              (tile0_gtpclkout0_i[1]),
        .DIVCLK                         (tile0_gtpclkout0_1_to_dcm_i),
        .IOCLK                          (),
        .SERDESSTROBE                   ()
    );

    assign  gtpclkout0_1_dcm1_reset_i       =  !tile0_plllkdet0_i;
    MGT_USRCLK_SOURCE #
    (
        .FREQUENCY_MODE                 ("LOW"),
        .DIVIDE_2                       ("FALSE"),
        .FEEDBACK                       ("1X"),
        .DIVIDE                         (4.0)
    )
    gtpclkout0_1_dcm1_i
    (
        .DIV1_OUT                       (tile0_rxusrclk0_i),
        .DIV2_OUT                       (tile0_rxusrclk20_i),
        .CLK2X_OUT                      (),
        .DCM_LOCKED_OUT                 (gtpclkout0_1_dcm1_locked_i),
        .CLK_IN                         (tile0_gtpclkout0_1_to_dcm_i),
        .FB_IN                          (tile0_rxusrclk0_i),
        .DCM_RESET_IN                   (gtpclkout0_1_dcm1_reset_i)
    );


    BUFIO2 #
    (
        .DIVIDE                         (1),
        .DIVIDE_BYPASS                  ("TRUE")
    )
    gtpclkout1_1_dcm2_bufio2_i
    (
        .I                              (tile0_gtpclkout1_i[1]),
        .DIVCLK                         (tile0_gtpclkout1_1_to_dcm_i),
        .IOCLK                          (),
        .SERDESSTROBE                   ()
    );

    assign  gtpclkout1_1_dcm2_reset_i       =  !tile0_plllkdet0_i;
    MGT_USRCLK_SOURCE #
    (
        .FREQUENCY_MODE                 ("LOW"),
        .DIVIDE_2                       ("FALSE"),
        .FEEDBACK                       ("1X"),
        .DIVIDE                         (4.0)
    )
    gtpclkout1_1_dcm2_i
    (
        .DIV1_OUT                       (tile0_rxusrclk1_i),
        .DIV2_OUT                       (tile0_rxusrclk21_i),
        .CLK2X_OUT                      (),
        .DCM_LOCKED_OUT                 (gtpclkout1_1_dcm2_locked_i),
        .CLK_IN                         (tile0_gtpclkout1_1_to_dcm_i),
        .FB_IN                          (tile0_rxusrclk1_i),
        .DCM_RESET_IN                   (gtpclkout1_1_dcm2_reset_i)
    );






    //--------------------------- The GTP Wrapper -----------------------------
    
    // Use the instantiation template in the examples directory to add the GTP wrapper to your design.
    // In this example, the wrapper is wired up for basic operation with a frame generator and frame 
    // checker. The GTPs will reset, then attempt to align and transmit data. If channel bonding is 
    // enabled, bonding should occur after alignment.


    // Wire all PLLLKDET signals to the top level as output ports
    assign TILE0_GTP0_PLLLKDET_OUT = tile0_plllkdet0_i;

    s6_gtpwizard_v1_11 #
    (
        .WRAPPER_SIM_GTPRESET_SPEEDUP           (EXAMPLE_SIM_GTPRESET_SPEEDUP),
        .WRAPPER_CLK25_DIVIDER_0                (3),
        .WRAPPER_CLK25_DIVIDER_1                (3),
        .WRAPPER_PLL_DIVSEL_FB_0                (4),
        .WRAPPER_PLL_DIVSEL_FB_1                (4),
        .WRAPPER_PLL_DIVSEL_REF_0               (1),
        .WRAPPER_PLL_DIVSEL_REF_1               (1),
        .WRAPPER_SIMULATION                     (EXAMPLE_SIMULATION)
    )
    s6_gtpwizard_v1_11_i
    (
 
 
 
 
 
 
 
        //_____________________________________________________________________
        //_____________________________________________________________________
        //TILE0  (X0_Y0)

        //---------------------- Loopback and Powerdown Ports ----------------------
        .TILE0_LOOPBACK0_IN             (tile0_loopback0_i),
        .TILE0_LOOPBACK1_IN             (tile0_loopback1_i),
        //------------------------------- PLL Ports --------------------------------
        .TILE0_CLK00_IN                 (tile0_gtp0_refclk_i),
        .TILE0_CLK01_IN                 (tied_to_ground_i),
        .TILE0_GTPRESET0_IN             (tile0_gtpreset0_i),
        .TILE0_GTPRESET1_IN             (tile0_gtpreset0_i),
        .TILE0_PLLLKDET0_OUT            (tile0_plllkdet0_i),
        .TILE0_RESETDONE0_OUT           (tile0_resetdone0_i),
        .TILE0_RESETDONE1_OUT           (tile0_resetdone1_i),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .TILE0_RXCHARISCOMMA0_OUT       (tile0_rxchariscomma0_i),
        .TILE0_RXCHARISCOMMA1_OUT       (tile0_rxchariscomma1_i),
        .TILE0_RXCHARISK0_OUT           (tile0_rxcharisk0_i),
        .TILE0_RXCHARISK1_OUT           (tile0_rxcharisk1_i),
        .TILE0_RXDISPERR0_OUT           (tile0_rxdisperr0_i),
        .TILE0_RXDISPERR1_OUT           (tile0_rxdisperr1_i),
        .TILE0_RXNOTINTABLE0_OUT        (tile0_rxnotintable0_i),
        .TILE0_RXNOTINTABLE1_OUT        (tile0_rxnotintable1_i),
        .TILE0_RXRUNDISP0_OUT           (tile0_rxrundisp0_i),
        .TILE0_RXRUNDISP1_OUT           (tile0_rxrundisp1_i),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .TILE0_RXBYTEISALIGNED0_OUT     (tile0_rxbyteisaligned0_i),
        .TILE0_RXBYTEISALIGNED1_OUT     (tile0_rxbyteisaligned1_i),
        .TILE0_RXENMCOMMAALIGN0_IN      (tile0_rxenmcommaalign0_i),
        .TILE0_RXENMCOMMAALIGN1_IN      (tile0_rxenmcommaalign1_i),
        .TILE0_RXENPCOMMAALIGN0_IN      (tile0_rxenpcommaalign0_i),
        .TILE0_RXENPCOMMAALIGN1_IN      (tile0_rxenpcommaalign1_i),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .TILE0_RXDATA0_OUT              (tile0_rxdata0_i),
        .TILE0_RXDATA1_OUT              (tile0_rxdata1_i),
        .TILE0_RXRECCLK0_OUT            (tile0_rxrecclk0_i),
        .TILE0_RXRECCLK1_OUT            (tile0_rxrecclk1_i),
        .TILE0_RXRESET0_IN              (tile0_rxreset0_i),
        .TILE0_RXRESET1_IN              (tile0_rxreset1_i),
        .TILE0_RXUSRCLK0_IN             (tile0_rxusrclk0_i),
        .TILE0_RXUSRCLK1_IN             (tile0_rxusrclk1_i),
        .TILE0_RXUSRCLK20_IN            (tile0_rxusrclk20_i),
        .TILE0_RXUSRCLK21_IN            (tile0_rxusrclk21_i),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .TILE0_GATERXELECIDLE0_IN       (tied_to_ground_i),
        .TILE0_GATERXELECIDLE1_IN       (tied_to_ground_i),
        .TILE0_IGNORESIGDET0_IN         (tied_to_ground_i),
        .TILE0_IGNORESIGDET1_IN         (tied_to_ground_i),
        .TILE0_RXELECIDLE0_OUT          (tile0_rxelecidle0_i),
        .TILE0_RXELECIDLE1_OUT          (tile0_rxelecidle1_i),
        .TILE0_RXEQMIX0_IN              (tile0_rxeqmix0_i),
        .TILE0_RXEQMIX1_IN              (tile0_rxeqmix1_i),
        .TILE0_RXN0_IN                  (RXN_IN[0]),
        .TILE0_RXN1_IN                  (RXN_IN[1]),
        .TILE0_RXP0_IN                  (RXP_IN[0]),
        .TILE0_RXP1_IN                  (RXP_IN[1]),
        //--------- Receive Ports - RX Elastic Buffer and Phase Alignment ----------
        .TILE0_RXSTATUS0_OUT            (tile0_rxstatus0_i),
        .TILE0_RXSTATUS1_OUT            (tile0_rxstatus1_i),
        //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
        .TILE0_DADDR_IN                 (tied_to_ground_vec_i[7:0]),
        .TILE0_DCLK_IN                  (drp_clk_in_i),
        .TILE0_DEN_IN                   (tied_to_ground_i),
        .TILE0_DI_IN                    (tied_to_ground_vec_i[15:0]),
        .TILE0_DRDY_OUT                 (),
        .TILE0_DRPDO_OUT                (),
        .TILE0_DWE_IN                   (tied_to_ground_i),
        //-------------------------- TX/RX Datapath Ports --------------------------
        .TILE0_GTPCLKFBEAST_OUT         (tile0_gtpclkfbeast_i),
        .TILE0_GTPCLKFBWEST_OUT         (tile0_gtpclkfbwest_i),
        .TILE0_GTPCLKOUT0_OUT           (tile0_gtpclkout0_i),
        .TILE0_GTPCLKOUT1_OUT           (tile0_gtpclkout1_i),
        //----------------- Transmit Ports - 8b10b Encoder Control -----------------
        .TILE0_TXBYPASS8B10B0_IN        (tile0_txbypass8b10b0_i),
        .TILE0_TXBYPASS8B10B1_IN        (tile0_txbypass8b10b1_i),
        .TILE0_TXCHARDISPMODE0_IN       (tile0_txchardispmode0_i),
        .TILE0_TXCHARDISPMODE1_IN       (tile0_txchardispmode1_i),
        .TILE0_TXCHARDISPVAL0_IN        (tile0_txchardispval0_i),
        .TILE0_TXCHARDISPVAL1_IN        (tile0_txchardispval1_i),
        .TILE0_TXCHARISK0_IN            (tile0_txcharisk0_i),
        .TILE0_TXCHARISK1_IN            (tile0_txcharisk1_i),
        .TILE0_TXKERR0_OUT              (tile0_txkerr0_i),
        .TILE0_TXKERR1_OUT              (tile0_txkerr1_i),
        .TILE0_TXRUNDISP0_OUT           (tile0_txrundisp0_i),
        .TILE0_TXRUNDISP1_OUT           (tile0_txrundisp1_i),
        //------------- Transmit Ports - TX Buffer and Phase Alignment -------------
        .TILE0_TXENPMAPHASEALIGN0_IN    (tile0_txenpmaphasealign0_i),
        .TILE0_TXENPMAPHASEALIGN1_IN    (tile0_txenpmaphasealign1_i),
        .TILE0_TXPMASETPHASE0_IN        (tile0_txpmasetphase0_i),
        .TILE0_TXPMASETPHASE1_IN        (tile0_txpmasetphase1_i),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TILE0_TXDATA0_IN               (tile0_txdata0_i),
        .TILE0_TXDATA1_IN               (tile0_txdata1_i),
        .TILE0_TXOUTCLK0_OUT            (tile0_txoutclk0_i),
        .TILE0_TXOUTCLK1_OUT            (tile0_txoutclk1_i),
        .TILE0_TXRESET0_IN              (tile0_txreset0_i),
        .TILE0_TXRESET1_IN              (tile0_txreset1_i),
        .TILE0_TXUSRCLK0_IN             (tile0_txusrclk0_i),
        .TILE0_TXUSRCLK1_IN             (tile0_txusrclk0_i),
        .TILE0_TXUSRCLK20_IN            (tile0_txusrclk20_i),
        .TILE0_TXUSRCLK21_IN            (tile0_txusrclk20_i),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TILE0_TXDIFFCTRL0_IN           (tile0_txdiffctrl0_i),
        .TILE0_TXDIFFCTRL1_IN           (tile0_txdiffctrl1_i),
        .TILE0_TXN0_OUT                 (TXN_OUT[0]),
        .TILE0_TXN1_OUT                 (TXN_OUT[1]),
        .TILE0_TXP0_OUT                 (TXP_OUT[0]),
        .TILE0_TXP1_OUT                 (TXP_OUT[1]),
        .TILE0_TXPREEMPHASIS0_IN        (tile0_txpreemphasis0_i),
        .TILE0_TXPREEMPHASIS1_IN        (tile0_txpreemphasis1_i),
        //--------------- Transmit Ports - TX Ports for PCI Express ----------------
        .TILE0_TXELECIDLE0_IN           (tile0_txelecidle0_i),
        .TILE0_TXELECIDLE1_IN           (tile0_txelecidle1_i),
        //------------------- Transmit Ports - TX Ports for SATA -------------------
        .TILE0_TXCOMSTART0_IN           (tile0_txcomstart0_i),
        .TILE0_TXCOMSTART1_IN           (tile0_txcomstart1_i),
        .TILE0_TXCOMTYPE0_IN            (tile0_txcomtype0_i),
        .TILE0_TXCOMTYPE1_IN            (tile0_txcomtype1_i)


    );

    // Hold the TX in reset till the TX user clocks are stable
       assign tile0_txreset0_i =   !(tile0_plllkdet0_i && gtpclkout0_0_pll0_locked_i);
       assign tile0_txreset1_i =   !(tile0_plllkdet0_i && gtpclkout0_0_pll0_locked_i);

       assign tile0_rxreset0_i =   !(tile0_plllkdet0_i && gtpclkout0_1_dcm1_locked_i);
       assign tile0_rxreset1_i =   !(tile0_plllkdet0_i && gtpclkout1_1_dcm2_locked_i);




    //---------------------------- TXSYNC module ------------------------------
    // The TXSYNC module performs phase synchronization for all the active TX datapaths. It
    // waits for the user clocks to be stable, then drives the phase align signals on each
    // GTP. When phase synchronization is complete, it asserts SYNC_DONE
    
    // Include the tx_sync module in your own design to perform phase synchronization if
    // your protocol bypasses the TX Buffers
  
    
    s6_gtpwizard_v1_11_tx_sync #
    (
        .PLL_DIVSEL_OUT   (2)
    )
    tile0_txsync0_i 
    (
        .TXENPMAPHASEALIGN(tile0_txenpmaphasealign0_i),
        .TXPMASETPHASE(tile0_txpmasetphase0_i),
        .SYNC_DONE(tile0_tx_sync_done0_i),
        .USER_CLK(tile0_txusrclk20_i),
        .RESET(!tile0_resetdone0_r2)
    );

  
    
    s6_gtpwizard_v1_11_tx_sync #
    (
        .PLL_DIVSEL_OUT   (2)
    )
    tile0_txsync1_i 
    (
        .TXENPMAPHASEALIGN(tile0_txenpmaphasealign1_i),
        .TXPMASETPHASE(tile0_txpmasetphase1_i),
        .SYNC_DONE(tile0_tx_sync_done1_i),
        .USER_CLK(tile0_txusrclk20_i),
        .RESET(!tile0_resetdone1_r2)
    );





    //------------------------ User Module Resets -----------------------------
    // All the User Modules i.e. FRAME_GEN, FRAME_CHECK and the sync modules
    // are held in reset till the RESETDONE goes high. 
    // The RESETDONE is registered a couple of times on USRCLK2 and connected 
    // to the reset of the modules
    
    always @(posedge tile0_rxusrclk20_i or negedge tile0_resetdone0_i)
    begin
        if (!tile0_resetdone0_i )
        begin
            tile0_resetdone0_r    <=    1'b0;
            tile0_resetdone0_r2   <=    1'b0;
        end
        else
        begin
            tile0_resetdone0_r    <=    tile0_resetdone0_i;
            tile0_resetdone0_r2   <=    tile0_resetdone0_r;
        end
    end
    always @(posedge tile0_rxusrclk21_i or negedge tile0_resetdone1_i)
    begin
        if (!tile0_resetdone1_i )
        begin
            tile0_resetdone1_r    <=    1'b0;
            tile0_resetdone1_r2   <=    1'b0;
        end
        else
        begin
            tile0_resetdone1_r    <=    tile0_resetdone1_i;
            tile0_resetdone1_r2   <=    tile0_resetdone1_r;
        end
    end

    //---------------------------- Frame Generators ---------------------------
    // The example design uses Block RAM based frame generators to provide test
    // data to the GTPs for transmission. By default the frame generators are 
    // loaded with an incrementing data sequence that includes commas/alignment
    // characters for alignment. If your protocol uses channel bonding, the 
    // frame generator will also be preloaded with a channel bonding sequence.
    
    // You can modify the data transmitted by changing the INIT values of the frame
    // generator in this file. Pay careful attention to bit order and the spacing
    // of your control and alignment characters.

    FRAME_GEN #
    (
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .MEM_00(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_01(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_02(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_03(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_04(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_05(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_06(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_07(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_08(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_09(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_0C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_0D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_10(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_11(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_12(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_13(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_14(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_15(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_16(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_17(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_18(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_19(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_1C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_1D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_20(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_21(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_22(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_23(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_24(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_25(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_26(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_27(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_28(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_29(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_2C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_2D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_30(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_31(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_32(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_33(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_34(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_35(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_36(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_37(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_38(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_39(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_3C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_3D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEMP_00(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_01(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_02(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_03(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_04(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_05(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_06(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_07(256'h0000000000000000000000000000010000000000000000000000000000000100)
    )
    tile0_frame_gen0
    (
        // User Interface
        .TX_DATA                        ({tile0_txdata0_float_i,tile0_txdata0_i}),
        .TX_CHARISK                     (tile0_txcharisk0_i),
           
        // System Interface
        .USER_CLK                       (tile0_txusrclk20_i),
        .SYSTEM_RESET                   (tile0_tx_system_reset0_c)
    );
    
    FRAME_GEN #
    (
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .MEM_00(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_01(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_02(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_03(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_04(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_05(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_06(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_07(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_08(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_09(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_0C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_0D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_10(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_11(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_12(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_13(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_14(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_15(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_16(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_17(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_18(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_19(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_1C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_1D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_20(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_21(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_22(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_23(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_24(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_25(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_26(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_27(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_28(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_29(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_2C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_2D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_30(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_31(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_32(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_33(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_34(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_35(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_36(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_37(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_38(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_39(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_3C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_3D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEMP_00(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_01(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_02(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_03(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_04(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_05(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_06(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_07(256'h0000000000000000000000000000010000000000000000000000000000000100)
    )
    tile0_frame_gen1
    (
        // User Interface
        .TX_DATA                        ({tile0_txdata1_float_i,tile0_txdata1_i}),
        .TX_CHARISK                     (tile0_txcharisk1_i),
           
        // System Interface
        .USER_CLK                       (tile0_txusrclk20_i),
        .SYSTEM_RESET                   (tile0_tx_system_reset1_c)
    );
    


    //-------------------------------- Frame Checkers -------------------------
    // The example design uses Block RAM based frame checkers to verify incoming  
    // data. By default the frame generators are loaded with a data sequence that 
    // matches the outgoing sequence of the frame generators for the TX ports.
    
    // You can modify the expected data sequence by changing the INIT values of the frame
    // checkers in this file. Pay careful attention to bit order and the spacing
    // of your control and alignment characters.
    
    // When the frame checker receives data, it attempts to synchronise to the 
    // incoming pattern by looking for the first sequence in the pattern. Once it 
    // finds the first sequence, it increments through the sequence, and indicates an 
    // error whenever the next value received does not match the expected value.

    assign tile0_frame_check0_reset_i = (EXAMPLE_CONFIG_INDEPENDENT_LANES==0)?reset_on_data_error_i:tile0_matchn0_i;

    // tile0_frame_check0 is always connected to the lane with the start of char
    // and this lane starts off the data checking on all the other lanes. The INC_IN port is tied off
    assign tile0_inc_in0_i = 1'b0;

    FRAME_CHECK #
    (
        .RX_DATA_WIDTH(32),
        .USE_COMMA(1),
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .CONFIG_INDEPENDENT_LANES(1),
        .START_OF_PACKET_CHAR(8'hbc),
        .MEM_00(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_01(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_02(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_03(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_04(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_05(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_06(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_07(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_08(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_09(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_0C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_0D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_10(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_11(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_12(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_13(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_14(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_15(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_16(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_17(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_18(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_19(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_1C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_1D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_20(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_21(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_22(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_23(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_24(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_25(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_26(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_27(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_28(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_29(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_2C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_2D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_30(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_31(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_32(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_33(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_34(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_35(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_36(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_37(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_38(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_39(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_3C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_3D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEMP_00(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_01(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_02(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_03(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_04(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_05(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_06(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_07(256'h0000000000000000000000000000010000000000000000000000000000000100)
    )
    tile0_frame_check0
    (
        // MGT Interface
        .RX_DATA                        (tile0_rxdata0_i),  
        .RX_ENMCOMMA_ALIGN              (tile0_rxenmcommaalign0_i),
        .RX_ENPCOMMA_ALIGN              (tile0_rxenpcommaalign0_i),
        .RX_ENCHAN_SYNC                 ( ),
        .RX_CHANBOND_SEQ                (tied_to_ground_i),        
        // Control Interface
        .INC_IN                         (tile0_inc_in0_i),
        .INC_OUT                        (tile0_inc_out0_i),
        .PATTERN_MATCH_N                (tile0_matchn0_i),
        .RESET_ON_ERROR                 (tile0_frame_check0_reset_i),
        // System Interface
        .USER_CLK                       (tile0_rxusrclk20_i),
        .SYSTEM_RESET                   (tile0_rx_system_reset0_c),
        .ERROR_COUNT                    (tile0_error_count0_i),
        .TRACK_DATA                     (tile0_track_data0_i)
    );
    
    assign tile0_frame_check1_reset_i = (EXAMPLE_CONFIG_INDEPENDENT_LANES==0)?reset_on_data_error_i:tile0_matchn1_i;

    // tile0_frame_check0 is always connected to the lane with the start of char
    // and this lane starts off the data checking on all the other lanes. The INC_IN port is tied off
    assign tile0_inc_in1_i = 1'b0;

    FRAME_CHECK #
    (
        .RX_DATA_WIDTH(32),
        .USE_COMMA(1),
        .WORDS_IN_BRAM(EXAMPLE_WORDS_IN_BRAM),
        .CONFIG_INDEPENDENT_LANES(1),
        .START_OF_PACKET_CHAR(8'hbc),
        .MEM_00(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_01(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_02(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_03(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_04(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_05(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_06(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_07(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_08(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_09(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_0C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_0D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_0E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_0F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_10(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_11(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_12(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_13(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_14(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_15(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_16(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_17(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_18(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_19(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_1C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_1D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_1E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_1F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_20(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_21(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_22(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_23(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_24(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_25(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_26(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_27(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_28(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_29(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_2C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_2D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_2E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_2F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_30(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_31(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_32(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_33(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_34(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_35(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_36(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_37(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_38(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_39(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3A(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3B(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEM_3C(256'h1e1d1c1b1a191817161514131211100f0e0d0c0b0a0908bc0706050403020100),
        .MEM_3D(256'h3e3d3c3b3a393837363534333231302f2e2d2c2b2a292827262524232221201f),
        .MEM_3E(256'h5e5d5c5b5a595857565554535251504f4e4d4c4b4a494847464544434241403f),
        .MEM_3F(256'h7e7d7c7b7a797877767574737271706f6e6d6c6b6a696867666564636261605f),
        .MEMP_00(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_01(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_02(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_03(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_04(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_05(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_06(256'h0000000000000000000000000000010000000000000000000000000000000100),
        .MEMP_07(256'h0000000000000000000000000000010000000000000000000000000000000100)
    )
    tile0_frame_check1
    (
        // MGT Interface
        .RX_DATA                        (tile0_rxdata1_i),  
        .RX_ENMCOMMA_ALIGN              (tile0_rxenmcommaalign1_i),
        .RX_ENPCOMMA_ALIGN              (tile0_rxenpcommaalign1_i),
        .RX_ENCHAN_SYNC                 ( ),
        .RX_CHANBOND_SEQ                (tied_to_ground_i),        
        // Control Interface
        .INC_IN                         (tile0_inc_in1_i),
        .INC_OUT                        (tile0_inc_out1_i),
        .PATTERN_MATCH_N                (tile0_matchn1_i),
        .RESET_ON_ERROR                 (tile0_frame_check1_reset_i),
        // System Interface
        .USER_CLK                       (tile0_rxusrclk21_i),
        .SYSTEM_RESET                   (tile0_rx_system_reset1_c),
        .ERROR_COUNT                    (tile0_error_count1_i),
        .TRACK_DATA                     (tile0_track_data1_i)
    );
    

    assign TRACK_DATA_OUT = track_data_out_i;

    assign track_data_out_i = 
                                tile0_track_data0_i &
                                tile0_track_data1_i ;


    
    assign reset_on_data_error_i = 1'b0; 

    //--------------------------- Chipscope Connections -----------------------
    // When the example design is run in hardware, it uses chipscope to allow the
    // example design and GTP wrapper to be controlled and monitored. The 
    // EXAMPLE_USE_CHIPSCOPE parameter allows chipscope to be removed for simulation.
    
generate
if (EXAMPLE_USE_CHIPSCOPE==1) 
begin : chipscope


    // Shared VIO for all tiles
    shared_vio shared_vio_i
    (
      .control                          (shared_vio_control_i),
      .async_in                         (shared_vio_in_i),
      .async_out                        (shared_vio_out_i)
    );
    
    // ICON for all VIOs 
    icon i_icon
    (
      .control0                         (shared_vio_control_i),
      .control1                         (tile0_data_vio_control_i),
      .control2                         (tile0_gtp0_ila_control_i),
      .control3                         (tile0_gtp1_ila_control_i),
      .control4                         (null_vio_4_i),
      .control5                         (null_vio_5_i),
      .control6                         (null_vio_6_i),
      .control7                         (null_vio_7_i),
      .control8                         (null_vio_8_i),
      .control9                         (null_vio_9_i),
      .control10                        (null_vio_10_i),
      .control11                        (null_vio_11_i),
      .control12                        (null_vio_12_i)
    );

    // TILE0 DATA VIO 
    data_vio tile0_data_vio_i
    (
      .control                          (tile0_data_vio_control_i),
      .async_in                         (tile0_data_vio_in_i),
      .async_out                        (tile0_data_vio_out_i)  
    );      

    // TILE0 GTP0 RX ILA 
    ila tile0_gtp0_i
    (
      .control                          (tile0_gtp0_ila_control_i),
      .clk                              (tile0_rxusrclk20_i),
      .trig0                            (tile0_ila_in0_i)
    );

    // TILE0 GTP1 RX ILA 
    ila tile0_gtp1_i
    (
      .control                          (tile0_gtp1_ila_control_i),
      .clk                              (tile0_rxusrclk21_i),
      .trig0                            (tile0_ila_in1_i)
    );



    null_vio i_null_vio_4
    (
      .control                          (null_vio_4_i)
    );
    
    null_vio i_null_vio_5
    (
      .control                          (null_vio_5_i)
    );
    
    null_vio i_null_vio_6
    (
      .control                          (null_vio_6_i)
    );
    
    null_vio i_null_vio_7
    (
      .control                          (null_vio_7_i)
    );
    
    null_vio i_null_vio_8
    (
      .control                          (null_vio_8_i)
    );
    
    null_vio i_null_vio_9
    (
      .control                          (null_vio_9_i)
    );
    
    null_vio i_null_vio_10
    (
      .control                          (null_vio_10_i)
    );
    
    null_vio i_null_vio_11
    (
      .control                          (null_vio_11_i)
    );
    
    null_vio i_null_vio_12
    (
      .control                          (null_vio_12_i)
    );
    


    // assign resets for frame_gen and frame_check modules
    assign  tile0_tx_system_reset0_c = !tile0_tx_sync_done0_i || user_tx_reset_i;
    assign  tile0_tx_system_reset1_c = !tile0_tx_sync_done1_i || user_tx_reset_i;
    assign  tile0_rx_system_reset0_c = !tile0_resetdone0_r2 || user_rx_reset_i;
    assign  tile0_rx_system_reset1_c = !tile0_resetdone1_r2 || user_rx_reset_i;


    assign  tile0_gtpreset0_i = gtpreset0_i;
 
    assign  tile0_gtpreset1_i = gtpreset0_i;


    // Shared VIO Outputs
    assign  gtpreset0_i                     =  shared_vio_out_i[31];
    assign  user_tx_reset_i                 =  shared_vio_out_i[30];
    assign  user_rx_reset_i                 =  shared_vio_out_i[29];

    // Shared VIO Inputs
    assign  shared_vio_in_i[31]             =  tile0_plllkdet0_i;
    assign  shared_vio_in_i[30:0]           =  tied_to_ground_vec_i[30:0];

    // Chipscope VIO input connections on Tile 0
    assign  tile0_data_vio_in_i[139]        =  tile0_resetdone0_i;
    assign  tile0_data_vio_in_i[138]        =  tile0_resetdone1_i;
    assign  tile0_data_vio_in_i[137:134]    =  tile0_txkerr0_i;
    assign  tile0_data_vio_in_i[133:130]    =  tile0_txkerr1_i;
    assign  tile0_data_vio_in_i[129:126]    =  tile0_txrundisp0_i;
    assign  tile0_data_vio_in_i[125:122]    =  tile0_txrundisp1_i;
    assign  tile0_data_vio_in_i[121:0]      =  tied_to_ground_vec_i[121:0];

    // Chipscope VIO ouptut connections on Tile 0
    assign  tile0_loopback0_i               =  tile0_data_vio_out_i[139:137];
    assign  tile0_loopback1_i               =  tile0_data_vio_out_i[136:134];
    assign  tile0_rxeqmix0_i                =  tile0_data_vio_out_i[133:132];
    assign  tile0_rxeqmix1_i                =  tile0_data_vio_out_i[131:130];
    assign  tile0_txbypass8b10b0_i          =  tile0_data_vio_out_i[129:126];
    assign  tile0_txbypass8b10b1_i          =  tile0_data_vio_out_i[125:122];
    assign  tile0_txchardispmode0_i         =  tile0_data_vio_out_i[121:118];
    assign  tile0_txchardispmode1_i         =  tile0_data_vio_out_i[117:114];
    assign  tile0_txchardispval0_i          =  tile0_data_vio_out_i[113:110];
    assign  tile0_txchardispval1_i          =  tile0_data_vio_out_i[109:106];
    assign  tile0_txdiffctrl0_i             =  tile0_data_vio_out_i[105:102];
    assign  tile0_txdiffctrl1_i             =  tile0_data_vio_out_i[101:98];
    assign  tile0_txpreemphasis0_i          =  tile0_data_vio_out_i[97:95];
    assign  tile0_txpreemphasis1_i          =  tile0_data_vio_out_i[94:92];
    assign  tile0_txelecidle0_i             =  tile0_data_vio_out_i[91];
    assign  tile0_txelecidle1_i             =  tile0_data_vio_out_i[90];
    assign  tile0_txcomstart0_i             =  tile0_data_vio_out_i[89];
    assign  tile0_txcomstart1_i             =  tile0_data_vio_out_i[88];
    assign  tile0_txcomtype0_i              =  tile0_data_vio_out_i[87];
    assign  tile0_txcomtype1_i              =  tile0_data_vio_out_i[86];

    // Chipscope ILA connections for GTP0 on Tile 0
    assign  tile0_ila_in0_i[84:81]          =  tile0_rxchariscomma0_i;
    assign  tile0_ila_in0_i[80:77]          =  tile0_rxcharisk0_i;
    assign  tile0_ila_in0_i[76:73]          =  tile0_rxdisperr0_i;
    assign  tile0_ila_in0_i[72:69]          =  tile0_rxnotintable0_i;
    assign  tile0_ila_in0_i[68:65]          =  tile0_rxrundisp0_i;
    assign  tile0_ila_in0_i[64]             =  tile0_rxbyteisaligned0_i;
    assign  tile0_ila_in0_i[63:32]          =  tile0_rxdata0_i;
    assign  tile0_ila_in0_i[31]             =  tile0_rxelecidle0_i;
    assign  tile0_ila_in0_i[30:28]          =  tile0_rxstatus0_i;
    assign  tile0_ila_in0_i[27:20]          =  tile0_error_count0_i;
    assign  tile0_ila_in0_i[19:0]           =  tied_to_ground_vec_i[19:0];

    // Chipscope ILA connections for GTP1 on Tile 0
    assign  tile0_ila_in1_i[84:81]          =  tile0_rxchariscomma1_i;
    assign  tile0_ila_in1_i[80:77]          =  tile0_rxcharisk1_i;
    assign  tile0_ila_in1_i[76:73]          =  tile0_rxdisperr1_i;
    assign  tile0_ila_in1_i[72:69]          =  tile0_rxnotintable1_i;
    assign  tile0_ila_in1_i[68:65]          =  tile0_rxrundisp1_i;
    assign  tile0_ila_in1_i[64]             =  tile0_rxbyteisaligned1_i;
    assign  tile0_ila_in1_i[63:32]          =  tile0_rxdata1_i;
    assign  tile0_ila_in1_i[31]             =  tile0_rxelecidle1_i;
    assign  tile0_ila_in1_i[30:28]          =  tile0_rxstatus1_i;
    assign  tile0_ila_in1_i[27:20]          =  tile0_error_count1_i;
    assign  tile0_ila_in1_i[19:0]           =  tied_to_ground_vec_i[19:0];




   
end //end EXAMPLE_USE_CHIPSCOPE=1 generate section
else
begin: no_chipscope

    // If Chipscope is not being used, drive GTP reset signal
    // from the top level ports
    assign  tile0_gtpreset0_i = GTP0_RESET_IN;
    assign  tile0_gtpreset1_i = GTP1_RESET_IN;

    // assign resets for frame_gen modules
    assign  tile0_tx_system_reset0_c = !tile0_tx_sync_done0_i;
    assign  tile0_tx_system_reset1_c = !tile0_tx_sync_done1_i;

    // assign resets for frame_check modules
    assign  tile0_rx_system_reset0_c = !tile0_resetdone0_r2;
    assign  tile0_rx_system_reset1_c = !tile0_resetdone1_r2;

    assign  gtpreset0_i                     =  tied_to_ground_i;
    assign  user_tx_reset_i                 =  tied_to_ground_i;
    assign  user_rx_reset_i                 =  tied_to_ground_i;
    assign  tile0_loopback0_i               =  tied_to_ground_vec_i[2:0];
    assign  tile0_loopback1_i               =  tied_to_ground_vec_i[2:0];
    assign  tile0_rxeqmix0_i                =  tied_to_ground_vec_i[1:0];
    assign  tile0_rxeqmix1_i                =  tied_to_ground_vec_i[1:0];
    assign  tile0_txbypass8b10b0_i          =  tied_to_ground_vec_i[3:0];
    assign  tile0_txbypass8b10b1_i          =  tied_to_ground_vec_i[3:0];
    assign  tile0_txchardispmode0_i         =  tied_to_ground_vec_i[3:0];
    assign  tile0_txchardispmode1_i         =  tied_to_ground_vec_i[3:0];
    assign  tile0_txchardispval0_i          =  tied_to_ground_vec_i[3:0];
    assign  tile0_txchardispval1_i          =  tied_to_ground_vec_i[3:0];
    assign  tile0_txdiffctrl0_i             =  tied_to_ground_vec_i[3:0];
    assign  tile0_txdiffctrl1_i             =  tied_to_ground_vec_i[3:0];
    assign  tile0_txpreemphasis0_i          =  tied_to_ground_vec_i[2:0];
    assign  tile0_txpreemphasis1_i          =  tied_to_ground_vec_i[2:0];
    assign  tile0_txelecidle0_i             =  tied_to_ground_i;
    assign  tile0_txelecidle1_i             =  tied_to_ground_i;
    assign  tile0_txcomstart0_i             =  tied_to_ground_i;
    assign  tile0_txcomstart1_i             =  tied_to_ground_i;
    assign  tile0_txcomtype0_i              =  tied_to_ground_i;
    assign  tile0_txcomtype1_i              =  tied_to_ground_i;



end
endgenerate //End generate for EXAMPLE_USE_CHIPSCOPE


endmodule

//-------------------------------------------------------------------
//
//  VIO core module declaration 
//  This one is for driving shared ports and is asynchronous
//
//-------------------------------------------------------------------
module shared_vio
  (
    control,
    async_in,
    async_out
  );
  inout  [35:0] control;
  input  [31:0] async_in;
  output [31:0] async_out;
endmodule


//-------------------------------------------------------------------
//
//  VIO core module declaration 
//  This one is for driving shared ports and is asynchronous
//
//-------------------------------------------------------------------
module data_vio
  (
    control,
    async_in,
    async_out
  );
  inout  [35:0] control;
  input  [139:0] async_in;
  output [139:0] async_out;
endmodule

//-------------------------------------------------------------------
//
//  ICON core module declaration
//
//-------------------------------------------------------------------
module icon 
  (
      control0,
      control1,
      control2,
      control3,
      control4,
      control5,
      control6,
      control7,
      control8,
      control9,
      control10,
      control11,
      control12
  );
  inout [35:0] control0;
  inout [35:0] control1;
  inout [35:0] control2;
  inout [35:0] control3;
  inout [35:0] control4;
  inout [35:0] control5;
  inout [35:0] control6;
  inout [35:0] control7;
  inout [35:0] control8;
  inout [35:0] control9;
  inout [35:0] control10;
  inout [35:0] control11;
  inout [35:0] control12;
endmodule


//-------------------------------------------------------------------
//
//  ILA core module declaration
//  This is used to allow RX signals to be monitored
//
//-------------------------------------------------------------------
module ila
  (
    control,
    clk,
    trig0
  );
  inout [35:0] control;
  input clk;
  input [84:0] trig0;
endmodule


//-------------------------------------------------------------------
//
//  NULL VIO core module declaration
//
//-------------------------------------------------------------------
module null_vio
  (
    control
  );
  inout [35:0] control;
endmodule

